[package]
name = "sticky_frame"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
video-rs = { version = "0.10.5", features = ["ndarray"] }
indicatif = "0.18.1"
rayon = "1.11.0"
env_logger = "0.11.8"
log = "0.4.28"
